name: Install dependencies

description: Install dependencies
inputs:
  workingDirectory:
    description: "The working directory to install dependencies in"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: socketdev/action@937f824ec476dfd164d4a4d9995751427b0be143 # v1
      with:
        mode: firewall

    - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1
      with:
        node-version: "24"
        cache: true

    - name: Install pnpm
      uses: pnpm/action-setup@v6
      with:
        version: "11.5.2"

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.workingDirectory }}
        sfw pnpm install --frozen-lockfile
