/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authDownloadRecoveryKeyRouteImport } from './routes/(auth)/download-recovery-key'
import { Route as dashboardVolumesIndexRouteImport } from './routes/(dashboard)/volumes/index'
import { Route as dashboardRepositoriesIndexRouteImport } from './routes/(dashboard)/repositories/index'
import { Route as dashboardBackupsIndexRouteImport } from './routes/(dashboard)/backups/index'
import { Route as dashboardVolumesVolumeIdRouteImport } from './routes/(dashboard)/volumes/$volumeId'
import { Route as dashboardRepositoriesCreateRouteImport } from './routes/(dashboard)/repositories/create'
import { Route as dashboardRepositoriesRepositoryIdRouteImport } from './routes/(dashboard)/repositories/$repositoryId'
import { Route as dashboardBackupsCreateRouteImport } from './routes/(dashboard)/backups/create'
import { Route as dashboardBackupsScheduleIdRouteImport } from './routes/(dashboard)/backups/$scheduleId'
import { Route as dashboardRepositoriesRepoIdSnapshotIdRouteImport } from './routes/(dashboard)/repositories/$repoId.$snapshotId'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDownloadRecoveryKeyRoute = authDownloadRecoveryKeyRouteImport.update({
  id: '/(auth)/download-recovery-key',
  path: '/download-recovery-key',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardVolumesIndexRoute = dashboardVolumesIndexRouteImport.update({
  id: '/volumes/',
  path: '/volumes/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardRepositoriesIndexRoute =
  dashboardRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardBackupsIndexRoute = dashboardBackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardVolumesVolumeIdRoute =
  dashboardVolumesVolumeIdRouteImport.update({
    id: '/volumes/$volumeId',
    path: '/volumes/$volumeId',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesCreateRoute =
  dashboardRepositoriesCreateRouteImport.update({
    id: '/repositories/create',
    path: '/repositories/create',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesRepositoryIdRoute =
  dashboardRepositoriesRepositoryIdRouteImport.update({
    id: '/repositories/$repositoryId',
    path: '/repositories/$repositoryId',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardBackupsCreateRoute = dashboardBackupsCreateRouteImport.update({
  id: '/backups/create',
  path: '/backups/create',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardBackupsScheduleIdRoute =
  dashboardBackupsScheduleIdRouteImport.update({
    id: '/backups/$scheduleId',
    path: '/backups/$scheduleId',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardRepositoriesRepoIdSnapshotIdRoute =
  dashboardRepositoriesRepoIdSnapshotIdRouteImport.update({
    id: '/repositories/$repoId/$snapshotId',
    path: '/repositories/$repoId/$snapshotId',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download-recovery-key': typeof authDownloadRecoveryKeyRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRoute
  '/backups/$scheduleId': typeof dashboardBackupsScheduleIdRoute
  '/backups/create': typeof dashboardBackupsCreateRoute
  '/repositories/$repositoryId': typeof dashboardRepositoriesRepositoryIdRoute
  '/repositories/create': typeof dashboardRepositoriesCreateRoute
  '/volumes/$volumeId': typeof dashboardVolumesVolumeIdRoute
  '/backups/': typeof dashboardBackupsIndexRoute
  '/repositories/': typeof dashboardRepositoriesIndexRoute
  '/volumes/': typeof dashboardVolumesIndexRoute
  '/repositories/$repoId/$snapshotId': typeof dashboardRepositoriesRepoIdSnapshotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download-recovery-key': typeof authDownloadRecoveryKeyRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRoute
  '/backups/$scheduleId': typeof dashboardBackupsScheduleIdRoute
  '/backups/create': typeof dashboardBackupsCreateRoute
  '/repositories/$repositoryId': typeof dashboardRepositoriesRepositoryIdRoute
  '/repositories/create': typeof dashboardRepositoriesCreateRoute
  '/volumes/$volumeId': typeof dashboardVolumesVolumeIdRoute
  '/backups': typeof dashboardBackupsIndexRoute
  '/repositories': typeof dashboardRepositoriesIndexRoute
  '/volumes': typeof dashboardVolumesIndexRoute
  '/repositories/$repoId/$snapshotId': typeof dashboardRepositoriesRepoIdSnapshotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/download-recovery-key': typeof authDownloadRecoveryKeyRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(dashboard)/backups/$scheduleId': typeof dashboardBackupsScheduleIdRoute
  '/(dashboard)/backups/create': typeof dashboardBackupsCreateRoute
  '/(dashboard)/repositories/$repositoryId': typeof dashboardRepositoriesRepositoryIdRoute
  '/(dashboard)/repositories/create': typeof dashboardRepositoriesCreateRoute
  '/(dashboard)/volumes/$volumeId': typeof dashboardVolumesVolumeIdRoute
  '/(dashboard)/backups/': typeof dashboardBackupsIndexRoute
  '/(dashboard)/repositories/': typeof dashboardRepositoriesIndexRoute
  '/(dashboard)/volumes/': typeof dashboardVolumesIndexRoute
  '/(dashboard)/repositories/$repoId/$snapshotId': typeof dashboardRepositoriesRepoIdSnapshotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download-recovery-key'
    | '/login'
    | '/onboarding'
    | '/backups/$scheduleId'
    | '/backups/create'
    | '/repositories/$repositoryId'
    | '/repositories/create'
    | '/volumes/$volumeId'
    | '/backups/'
    | '/repositories/'
    | '/volumes/'
    | '/repositories/$repoId/$snapshotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download-recovery-key'
    | '/login'
    | '/onboarding'
    | '/backups/$scheduleId'
    | '/backups/create'
    | '/repositories/$repositoryId'
    | '/repositories/create'
    | '/volumes/$volumeId'
    | '/backups'
    | '/repositories'
    | '/volumes'
    | '/repositories/$repoId/$snapshotId'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)'
    | '/(auth)/download-recovery-key'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/(dashboard)/backups/$scheduleId'
    | '/(dashboard)/backups/create'
    | '/(dashboard)/repositories/$repositoryId'
    | '/(dashboard)/repositories/create'
    | '/(dashboard)/volumes/$volumeId'
    | '/(dashboard)/backups/'
    | '/(dashboard)/repositories/'
    | '/(dashboard)/volumes/'
    | '/(dashboard)/repositories/$repoId/$snapshotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  authDownloadRecoveryKeyRoute: typeof authDownloadRecoveryKeyRoute
  authLoginRoute: typeof authLoginRoute
  authOnboardingRoute: typeof authOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/download-recovery-key': {
      id: '/(auth)/download-recovery-key'
      path: '/download-recovery-key'
      fullPath: '/download-recovery-key'
      preLoaderRoute: typeof authDownloadRecoveryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/volumes/': {
      id: '/(dashboard)/volumes/'
      path: '/volumes'
      fullPath: '/volumes/'
      preLoaderRoute: typeof dashboardVolumesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/': {
      id: '/(dashboard)/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof dashboardRepositoriesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/': {
      id: '/(dashboard)/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof dashboardBackupsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/volumes/$volumeId': {
      id: '/(dashboard)/volumes/$volumeId'
      path: '/volumes/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof dashboardVolumesVolumeIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/create': {
      id: '/(dashboard)/repositories/create'
      path: '/repositories/create'
      fullPath: '/repositories/create'
      preLoaderRoute: typeof dashboardRepositoriesCreateRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/$repositoryId': {
      id: '/(dashboard)/repositories/$repositoryId'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof dashboardRepositoriesRepositoryIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/create': {
      id: '/(dashboard)/backups/create'
      path: '/backups/create'
      fullPath: '/backups/create'
      preLoaderRoute: typeof dashboardBackupsCreateRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/backups/$scheduleId': {
      id: '/(dashboard)/backups/$scheduleId'
      path: '/backups/$scheduleId'
      fullPath: '/backups/$scheduleId'
      preLoaderRoute: typeof dashboardBackupsScheduleIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/repositories/$repoId/$snapshotId': {
      id: '/(dashboard)/repositories/$repoId/$snapshotId'
      path: '/repositories/$repoId/$snapshotId'
      fullPath: '/repositories/$repoId/$snapshotId'
      preLoaderRoute: typeof dashboardRepositoriesRepoIdSnapshotIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardBackupsScheduleIdRoute: typeof dashboardBackupsScheduleIdRoute
  dashboardBackupsCreateRoute: typeof dashboardBackupsCreateRoute
  dashboardRepositoriesRepositoryIdRoute: typeof dashboardRepositoriesRepositoryIdRoute
  dashboardRepositoriesCreateRoute: typeof dashboardRepositoriesCreateRoute
  dashboardVolumesVolumeIdRoute: typeof dashboardVolumesVolumeIdRoute
  dashboardBackupsIndexRoute: typeof dashboardBackupsIndexRoute
  dashboardRepositoriesIndexRoute: typeof dashboardRepositoriesIndexRoute
  dashboardVolumesIndexRoute: typeof dashboardVolumesIndexRoute
  dashboardRepositoriesRepoIdSnapshotIdRoute: typeof dashboardRepositoriesRepoIdSnapshotIdRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardBackupsScheduleIdRoute: dashboardBackupsScheduleIdRoute,
  dashboardBackupsCreateRoute: dashboardBackupsCreateRoute,
  dashboardRepositoriesRepositoryIdRoute:
    dashboardRepositoriesRepositoryIdRoute,
  dashboardRepositoriesCreateRoute: dashboardRepositoriesCreateRoute,
  dashboardVolumesVolumeIdRoute: dashboardVolumesVolumeIdRoute,
  dashboardBackupsIndexRoute: dashboardBackupsIndexRoute,
  dashboardRepositoriesIndexRoute: dashboardRepositoriesIndexRoute,
  dashboardVolumesIndexRoute: dashboardVolumesIndexRoute,
  dashboardRepositoriesRepoIdSnapshotIdRoute:
    dashboardRepositoriesRepoIdSnapshotIdRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  authDownloadRecoveryKeyRoute: authDownloadRecoveryKeyRoute,
  authLoginRoute: authLoginRoute,
  authOnboardingRoute: authOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
