/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRecoveryKeyRouteImport } from './routes/download-recovery-key'
import { Route as IndexRouteImport } from './routes/index'

const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRecoveryKeyRoute = DownloadRecoveryKeyRouteImport.update({
  id: '/download-recovery-key',
  path: '/download-recovery-key',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download-recovery-key': typeof DownloadRecoveryKeyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/volumes': typeof VolumesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download-recovery-key': typeof DownloadRecoveryKeyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/volumes': typeof VolumesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download-recovery-key': typeof DownloadRecoveryKeyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/volumes': typeof VolumesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download-recovery-key'
    | '/login'
    | '/onboarding'
    | '/volumes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download-recovery-key' | '/login' | '/onboarding' | '/volumes'
  id:
    | '__root__'
    | '/'
    | '/download-recovery-key'
    | '/login'
    | '/onboarding'
    | '/volumes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRecoveryKeyRoute: typeof DownloadRecoveryKeyRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  VolumesRoute: typeof VolumesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-recovery-key': {
      id: '/download-recovery-key'
      path: '/download-recovery-key'
      fullPath: '/download-recovery-key'
      preLoaderRoute: typeof DownloadRecoveryKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRecoveryKeyRoute: DownloadRecoveryKeyRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VolumesRoute: VolumesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
