FROM oven/bun:latest

RUN apt-get update && apt-get install -y \
    cifs-utils \
    nfs-common \
    davfs2 \
    sshfs \
    kmod \
    iputils-ping \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

