name: Docs deploy
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install dependencies
        uses: "./.github/actions/install-dependencies"
        with:
          workingDirectory: docs

      - name: Build docs
        working-directory: docs
        run: bun run build

      - name: Build and deploy docs
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: docs






